version: "2.3"
networks:
  cassandra-final:
services:
  cass1:
    image: cassandra
    container_name: cass1
    hostname: cass1
    mem_limit: 2048M
    mem_reservation: 512M
    # cpus: 0.2
    networks: 
      - cassandra-final
    ports:
      - "9042:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra
    environment: &environment
      CASSANDRA_SEEDS: "cass1,cass2"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: FinalProject
  cass2:
    image: cassandra
    container_name: cass2
    hostname: cass2
    networks: 
      - cassandra-final
    mem_limit: 2048M
    mem_reservation: 512M
    # cpus: 0.2
    ports:
      - "9043:9042"
    volumes:
      - ./data/cass2:/var/lib/cassandra
    environment: *environment
    depends_on: 
      - cass1
  cass3:
    image: cassandra
    container_name: cass3
    hostname: cass3
    mem_limit: 2048M
    mem_reservation: 512M
    networks: 
      - cassandra-final
    ports:
      - "9044:9042"
    volumes:
      - ./data/cass3:/var/lib/cassandra
    environment: *environment
    depends_on: 
      - cass2