version: "2.3"
services:
  mysql1:
    image: mysql
    container_name: mysql1
    hostname: mysql1
    mem_limit: 6144M
    mem_reservation: 1536M
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment: &environment
      MYSQL_ROOT_PASSWORD: root